apiVersion: v1
kind: ConfigMap
metadata:
  name: config-01 # configMap name
data:
  my.conf: |
    [mysql] 
    innodb_redo_log_capacity=2G
---
apiVersion: v1
kind: Pod
metadata: 
  name: test-01
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: mysql-config
          mountPath:  /etc/mysql/conf.d/my.conf
          subPath: my.conf
  volumes:
    - name: mysql-config
      configMap:
        - name: config-01 # config map name it use as link
