---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 3
  selector:
    matchLables: ## selector and match labels only for deployment
      purpose: test-01
      company: d2
  template:
    metadata:
      labels:
        purpose: test-01
        company: d2
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: LoadBalancer
  selector:
      purpose: test-01
      company: d2
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    